LRQA-82611
manuferreira/liferay-portal pull request #62
Opened 2023-08-30 16:07 UTC by Claudioss23

2023-08-30 16:09 UTC, Claudioss23 commented
ci:test:sf

2023-08-30 16:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/4901/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4901/jenkins-report.html">here</a>.</b></p>

2023-09-05 19:35 UTC, Claudioss23 commented
ci:test:sf

2023-09-05 19:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/4818/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4818/jenkins-report.html">here</a>.</b></p>

2023-09-05 19:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2734632486accdb4ef0ea2df712365c77e85932">e2734632486accdb4ef0ea2df712365c77e85932</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Claudioss23/liferay-portal/tree/LRQA-82611">LRQA-82611</a><br/>Branch GIT ID: <a href="https://github.com/Claudioss23/liferay-portal/commit/6442bf7ba0ae1d208fdab9e6746492a805928904">6442bf7ba0ae1d208fdab9e6746492a805928904</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4818/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4818/jenkins-report.html">here</a>.</h5></details></html>

2023-09-05 19:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4818/">test-portal-source-format#4818</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4818/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/manuferreira/liferay-portal/pull/62">manuferreira#62</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419113804">[master] ci:test:sf - Claudioss23 &gt; manuferreira - PR#62 - 2023-09-05[12:36:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/18162/">publish-testray-report#18162</a><br/></div></div>

2023-09-11 14:14 UTC, manuferreira requested changes

2023-09-11 14:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/8101/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8101/jenkins-report.html">here</a>.</b></p>

2023-09-11 14:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d7210e871573904fcf486a55af02f57f5a2d2c74">d7210e871573904fcf486a55af02f57f5a2d2c74</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Claudioss23/liferay-portal/tree/LRQA-82611">LRQA-82611</a><br/>Branch GIT ID: <a href="https://github.com/Claudioss23/liferay-portal/commit/dee2ba5de208dc880e009a8ca1069c2f4e98b08d">dee2ba5de208dc880e009a8ca1069c2f4e98b08d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8101/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8101/jenkins-report.html">here</a>.</h5></details></html>

2023-09-11 14:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8101/">test-portal-source-format#8101</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8101/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/manuferreira/liferay-portal/pull/62">manuferreira#62</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2422110786">[master] ci:test:sf - Claudioss23 &gt; manuferreira - PR#62 - 2023-09-11[07:31:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/30780/">publish-testray-report#30780</a><br/></div></div>

2023-09-11 14:42 UTC, manuferreira approved these changes
LGTM. Thanks for working on it! :muscle:

2023-09-11 14:43 UTC, closed without merging